version: "3.9"
services:
  template:
    container_name: project_mirror
    image: project-mirror
    build:
      context: .
      dockerfile: ./Dockerfile'
    ports:
      - "5000:3000"
    privileged: true
    restart: always
    volumes:
      - ".data:/usr/local/app/.data"
      - "/etc/localtime:/etc/localtime:ro"